version: '3.4'

services:
  ecommerce-mysqldb:
    image: mysql:8.0.34
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ecommerce
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/mysql:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-network

  ecommerce-api:
    image: ecommerce-api
    build:
      context: .
      dockerfile: src/Ecommerce.Api/Dockerfile
    expose:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DBHOST=ecommerce-mysqldb
      - DB_CONNECTION=server=ecommerce-mysqldb;user=root;password=1234;database=ecommerce
    networks:
      - ecommerce-network
    depends_on:
      - ecommerce-mysqldb

  ecommerce-nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ecommerce-api
    ports:
      - 3000:3000
    networks:
      - ecommerce-network

networks:
  ecommerce-network:

volumes:
  mysql-data:
