# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  ecommerce-api:
    image: ecommerce-api
    build:
      context: .
      dockerfile: src/Ecommerce.Api/Dockerfile
    ports:
      - 5000:5000
